src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity
 */
class User implements UserInterface, \Serializable
{
	/**
	 * @ORM\Column(type="bigint")
	 * @ORM\Id
	 */
	protected $steamid;

	/**
	 * @ORM\Column(nullable=true)
	 */
	protected $avatar;

    /**
     * @ORM\Column(nullable=true)
     */
    protected $avatarmedium;

	/**
	 * @ORM\Column(type="datetime", name="created_at")
	 */
	protected $createdAt;

	/**
	 * @ORM\Column(type="datetime", name="updated_at", nullable=true)
	 */
	protected $updatedAt;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=4, nullable=true)
     */
    protected $rating;

    /**
     * @ORM\Column(type="boolean", name="is_being_handled")
     */
    protected $isBeingHandled = false;

    /**
     * @ORM\Column(type="integer", name="games_owned")
     */
    protected $gamesOwned = 0;

    /**
     * @ORM\Column(type="integer", name="hours_played")
     */
    protected $hoursPlayed = 0;

    /**
     * @ORM\OneToMany(targetEntity="UserGame", mappedBy="user")
     */
    protected $games;

    /**
     * @ORM\OneToMany(targetEntity="UserAchievement", mappedBy="user")
     */
    protected $achievements;

    /**
     * @ORM\Column(length=32)
     */
    protected $hash;

	/**
	 * Initialize default values
	 */
	public function __construct()
	{
		$this->createdAt    = new \DateTime();
        $this->hash         = md5(microtime() .'{'. mt_rand() .'}');
        $this->games        = new ArrayCollection();
        $this->achievements = new ArrayCollection();
	}

    /**
     * Set steamid
     *
     * @param integer $steamid
     *
     * @return User
     */
    public function setSteamid($steamid)
    {
        $this->steamid = $steamid;

        return $this;
    }

    /**
     * Get steamid
     *
     * @return integer
     */
    public function getSteamid()
    {
        return $this->steamid;
    }

    /**
     * Set avatar
     *
     * @param string $avatar
     *
     * @return User
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return User
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set rating
     *
     * @param string $rating
     *
     * @return User
     */
    public function setRating($rating)
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * Get rating
     *
     * @return string
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Set isBeingHandled
     *
     * @param boolean $isBeingHandled
     *
     * @return User
     */
    public function setIsBeingHandled($isBeingHandled)
    {
        $this->isBeingHandled = $isBeingHandled;

        return $this;
    }

    /**
     * Get isBeingHandled
     *
     * @return boolean
     */
    public function getIsBeingHandled()
    {
        return $this->isBeingHandled;
    }

    /**
     * Add game
     *
     * @param UserGame $game
     *
     * @return User
     */
    public function addGame(UserGame $game)
    {
        $this->games[] = $game;

        return $this;
    }

    /**
     * Remove game
     *
     * @param UserGame $game
     */
    public function removeGame(UserGame $game)
    {
        $this->games->removeElement($game);
    }

    /**
     * Get games
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGames()
    {
        return $this->games;
    }

    /**
     * Add achievement
     *
     * @param UserAchievement $achievement
     *
     * @return User
     */
    public function addAchievement(UserAchievement $achievement)
    {
        $this->achievements[] = $achievement;

        return $this;
    }

    /**
     * Remove achievement
     *
     * @param UserAchievement $achievement
     */
    public function removeAchievement(UserAchievement $achievement)
    {
        $this->achievements->removeElement($achievement);
    }

    /**
     * Get achievements
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAchievements()
    {
        return $this->achievements;
    }

    /**
     * {@inheritdoc}
     */
    public function getUsername()
    {
        return $this->getSteamid();
    }

    /**
     * {@inheritdoc}
     */
    public function getRoles()
    {
        return ['ROLE_STEAM_USER'];
    }

    /**
     * {@inheritdoc}
     */
    public function eraseCredentials()
    {}

    /**
     * {@inheritdoc}
     */
    public function getPassword()
    {}

    /**
     * {@inheritdoc}
     */
    public function getSalt()
    {}

    /**
     * {@inheritdoc}
     */
    public function serialize()
    {
        return serialize(array(
            $this->steamid
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function unserialize($serizlized)
    {
        list($this->steamid) = unserialize($serizlized);
    }

    /**
     * Check if the user data was updated more than 1 day ago or never been set
     *
     * @return bool
     */
    public function isOutdated()
    {
        if ($this->isBeingHandled) {
            return false;
        }

        if (
            $this->updatedAt instanceof \DateTime
            &&
            $this->updatedAt > new \DateTime('-1 day')
        ) {
            return false;
        }

        return true;
    }

    /**
     * Return the integer part of the rating
     *
     * @return integer
     */
    public function getRatingInteger()
    {
        if (null == $this->rating) {
            return 0;
        }

        return round($this->rating);
    }

    /**
     * Return the fractional part of the rating
     *
     * @return integer
     */
    public function getRatingFraction()
    {
        if (null == $this->rating) {
            return 0;
        }

        $ratingString = (string) $this->rating;

        if (false === strpos($ratingString, '.')) {
            return 0;
        }

        return preg_replace('/^\d+\./', '', $ratingString);
    }

    /**
     * Set hash
     *
     * @param string $hash
     *
     * @return User
     */
    public function setHash($hash)
    {
        $this->hash = $hash;

        return $this;
    }

    /**
     * Get hash
     *
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Set gamesOwned
     *
     * @param integer $gamesOwned
     *
     * @return User
     */
    public function setGamesOwned($gamesOwned)
    {
        $this->gamesOwned = $gamesOwned;

        return $this;
    }

    /**
     * Get gamesOwned
     *
     * @return integer
     */
    public function getGamesOwned()
    {
        return $this->gamesOwned;
    }

    /**
     * Set avatarmedium
     *
     * @param string $avatarmedium
     *
     * @return User
     */
    public function setAvatarmedium($avatarmedium)
    {
        $this->avatarmedium = $avatarmedium;

        return $this;
    }

    /**
     * Get avatarmedium
     *
     * @return string
     */
    public function getAvatarmedium()
    {
        return $this->avatarmedium;
    }

    /**
     * Set hoursPlayed
     *
     * @param integer $hoursPlayed
     *
     * @return User
     */
    public function setHoursPlayed($hoursPlayed)
    {
        $this->hoursPlayed = $hoursPlayed;

        return $this;
    }

    /**
     * Get hoursPlayed
     *
     * @return integer
     */
    public function getHoursPlayed()
    {
        return $this->hoursPlayed;
    }
}

src/AppBundle/Controller/UserController.php
<?php

namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Http\Event\InteractiveLoginEvent;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use AppBundle\Entity\User;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

class UserController extends Controller
{
    /**
     * @Route("/login", name="login")
     * @Method("GET")
     */
    public function loginAction(Request $request)
    {
    	if ($this->get('security.authorization_checker')->isGranted('ROLE_STEAM_USER')) {
    		return $this->redirectToRoute('user');
    	}

        $openid = new \LightOpenID($request->getHost());

        $openid->identity  = $this->container->getParameter('steam_identity');
        $openid->returnUrl = $this->generateUrl('auth', [], UrlGeneratorInterface::ABSOLUTE_URL);

        return $this->redirect($openid->authUrl());
    }

    /**
     * @Route("/auth", name="auth")
     * @Method("GET")
     */
    public function authAction(Request $request)
    {
        $openid = new \LightOpenID($request->getHost());

        if ($openid->mode == 'cancel' || !$openid->validate()) {
            return $this->redirectToRoute('homepage');
        }

        preg_match('/^.*\/(\d+)$/', $openid->identity, $matches);
        if (!isset($matches[1])) {
            return $this->redirectToRoute('homepage');
        }

        $user = $this->get('steam_data')->getUser($matches[1]);

        $token = new UsernamePasswordToken($user, null, 'main', $user->getRoles());
        $this->get('security.token_storage')->setToken($token);

        $event = new InteractiveLoginEvent($request, $token);
        $this->get('event_dispatcher')->dispatch('security.interactive_login', $event);
        
        return $this->redirectToRoute('user');
    }

    /**
     * @Route("/logout", name="logout")
     * @Method("GET")
     */
    public function logoutAction(Request $request)
    {
        $this->get('security.token_storage')->setToken(null);
        $request->getSession()->invalidate();

        return $this->redirectToRoute('homepage');
    }

    /**
     * @Route("/user", name="user")
     * @Method("GET")
     */
    public function userAction()
    {
        if (!$this->get('security.authorization_checker')->isGranted('ROLE_STEAM_USER')) {
            return $this->redirectToRoute('homepage');
        }

        if ($this->getUser()->isOutdated()) {
            $this->get('steam_data')->updateUser($this->getUser());
        }

        return $this->render('AppBundle:User:index.html.twig');
    }

    /**
     * @Route("/user/progress", name="user_progress")
     * @Method("GET")
     */
    public function progressAction(Request $request)
    {
        if (!$this->get('security.authorization_checker')->isGranted('ROLE_STEAM_USER')) {
            throw new AccessDeniedHttpException();
        }

        $data = $this->get('steam_data')->getUserProgress(
            $this->getUser()
        );

        $view = $this->renderView('AppBundle:User:progress.html.twig', $data);

        if ($request->isXmlHttpRequest()) {
            return new JsonResponse([
                'view' => $view,
                'stop' => !$data['in_progress']
            ]);
        }

        return new Response($view);
    }

    /**
     * @Route("/user/{hash}.png", name="user_bar", requirements={
     *      "hash": "\w{32}"
     * })
     * @Method("GET")
     */
    public function barAction($hash)
    {
        $em = $this->getDoctrine()->getManager();

        $user = $em->getRepository('AppBundle:User')->findOneByHash($hash);

        if (!$user instanceof User) {
            throw $this->createNotFoundException();
        }

        $image = $this->get('user_image')->getUserbar($user);
        
        return new Response(file_get_contents($image), 200, [
            'Content-Type' => 'image/png'
        ]);
    }

    /**
     * @Route("/user/{hash}", name="user_share", requirements={
     *      "hash": "\w{32}"
     * })
     * @Method("GET")
     */
    public function shareAction($hash)
    {
        $em = $this->getDoctrine()->getManager();

        $user = $em->getRepository('AppBundle:User')->findOneByHash($hash);

        if (!$user instanceof User) {
            throw $this->createNotFoundException();
        }

        $image = $this->get('user_image')->getShareImage($user);
        $image = str_replace($this->container->getParameter('web_path'), '', $image);

        return $this->render('AppBundle:User:shared.html.twig', [
            'user'  => $user,
            'image' => $image
        ]);
    }
}

src/AppBundle/Resources/views/User/card.html.twig
<div class="user-card">
    {% if user.isBeingHandled %}
        <div id="user-progress" data-url="{{ path('user_progress', { hash: user.hash }) }}">
            {{ render(controller('AppBundle:User:progress', {
                hash: user.hash
            })) }}
        </div>
    {% else %}
        <h2>your current rating:</h2>

        {{ include('AppBundle:User:result.html.twig') }}
    {% endif %}
</div>

src/AppBundle/Resources/views/User/index.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block content %}
    <div class="jumbotron">
        {{ include('AppBundle:User:card.html.twig', {
            user: app.user
        }) }}
    </div>

    <div id="user-share-block" class="jumbotron{{ app.user.isBeingHandled ? ' hidden' }}">
        {{ include('AppBundle:User:sharing.html.twig') }}
    </div>

    <div id="user-bar-block" class="jumbotron{{ app.user.isBeingHandled ? ' hidden' }}">
        {{ include('AppBundle:User:userbar.html.twig') }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/User/progress.html.twig
{% if status in ['games', 'achievements'] %}
    <h2>your rating is being calculated.</h2>

    just give as a minute. or a bit more...
    <br /><br />

    {% if status == 'games' %}
        updating the game list
    {% else %}
        updating achievements:
        <span class="text-success">
            {{ percentage | number_format(1) }}%
        </span>
    {% endif %}

    <img src="{{ asset('bundles/app/images/ball.gif') }}" />

{% else %}
    <h2>your current rating:</h2>

    {{ include('AppBundle:User:result.html.twig', {
        user: app.user
    }) }}
{% endif %}

src/AppBundle/Resources/views/User/rating.html.twig
<span class="text-success score-main">{{ user.ratingInteger | number_format }}</span>.{{ user.ratingFraction }}
s<span class="text-success">m</span>.

src/AppBundle/Resources/views/User/result.html.twig
<div class="result-left pull-left">
    <img src="{{ user.avatar }}" />

    {{ include('AppBundle:User:rating.html.twig') }}

    <br />

    <span class="user-dates text-muted">
        last update: {{ user.updatedAt | date('M j Y g:i a') }}
        <br />
        next update: {{ user.updatedAt | date_modify('+1 day') | date('M j Y g:i a') }}
    </span>
</div>

<div class="result-right pull-right">
    <div class="result-right-title pull-left">
        games&nbsp;&nbsp;owned:
    </div>
    <div class="result-right-value pull-right text-success">
        {{ user.gamesOwned | number_format }}
    </div>

    <div class="result-right-title pull-left">
        hours played:
    </div>
    <div class="result-right-value pull-right text-success">
        {{ user.hoursPlayed | number_format }}
    </div>

    <div class="result-right-title pull-left">
        achievements:
    </div>
    <div class="result-right-value pull-right text-success">
        {{ user.achievements | length | number_format }}
    </div>
</div>

<div class="clearfix"></div>

src/AppBundle/Resources/views/User/shared.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block meta %}
    {{ parent() }}

    {{ include('AppBundle::og.html.twig', {
        pageUrl:  path('user_share', { hash: user.hash }),
        imageUrl: image
    }) }}
{% endblock %}

{% block logout %}{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="user-card">
            <h2>player's rating:</h2>

            {{ include('AppBundle:User:result.html.twig') }}
        </div>
    </div>

    <div class="jumbotron">
        <h2>and what have you achieved?</h2>

        {% if is_granted('ROLE_STEAM_USER') %}
            <p>
                <a href="{{ path('user') }}">see your rating</a>.
            </p>
        {% else %}
            {{ include('AppBundle:Homepage:text.html.twig') }}
        {% endif %}
    </div>
{% endblock %}

src/AppBundle/Resources/views/User/sharing.html.twig
{% set siteUrl  = 'http://' ~ app.request.host %}
{% set shareUrl = siteUrl ~ path('user_share', { hash: app.user.hash }) %}
{% set imageUrl = siteUrl ~ '/sharing/' ~ app.user.hash ~ '.png' %}

<h2>share with your friends:</h2>

<p>
    they must know about your progress!
</p>

<ul class="rrssb-buttons">
    <li class="rrssb-facebook">
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ shareUrl }}" class="popup">
            <span class="rrssb-icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 29 29"><path d="M26.4 0H2.6C1.714 0 0 1.715 0 2.6v23.8c0 .884 1.715 2.6 2.6 2.6h12.393V17.988h-3.996v-3.98h3.997v-3.062c0-3.746 2.835-5.97 6.177-5.97 1.6 0 2.444.173 2.845.226v3.792H21.18c-1.817 0-2.156.9-2.156 2.168v2.847h5.045l-.66 3.978h-4.386V29H26.4c.884 0 2.6-1.716 2.6-2.6V2.6c0-.885-1.716-2.6-2.6-2.6z"/></svg>
            </span>
            <span class="rrssb-text">facebook</span>
        </a>
    </li>

    <li class="rrssb-twitter">
        <a href="https://twitter.com/intent/tweet?text={{ ('Measure your coolness on steameter.com | ' ~ imageUrl) | url_encode }}"
        class="popup">
            <span class="rrssb-icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><path d="M24.253 8.756C24.69 17.08 18.297 24.182 9.97 24.62a15.093 15.093 0 0 1-8.86-2.32c2.702.18 5.375-.648 7.507-2.32a5.417 5.417 0 0 1-4.49-3.64c.802.13 1.62.077 2.4-.154a5.416 5.416 0 0 1-4.412-5.11 5.43 5.43 0 0 0 2.168.387A5.416 5.416 0 0 1 2.89 4.498a15.09 15.09 0 0 0 10.913 5.573 5.185 5.185 0 0 1 3.434-6.48 5.18 5.18 0 0 1 5.546 1.682 9.076 9.076 0 0 0 3.33-1.317 5.038 5.038 0 0 1-2.4 2.942 9.068 9.068 0 0 0 3.02-.85 5.05 5.05 0 0 1-2.48 2.71z"/></svg>
            </span>
            <span class="rrssb-text">twitter</span>
        </a>
    </li>

    <li class="rrssb-googleplus">
        <a href="https://plus.google.com/share?url={{ shareUrl }}" class="popup">
            <span class="rrssb-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M21 8.29h-1.95v2.6h-2.6v1.82h2.6v2.6H21v-2.6h2.6v-1.885H21V8.29zM7.614 10.306v2.925h3.9c-.26 1.69-1.755 2.925-3.9 2.925-2.34 0-4.29-2.016-4.29-4.354s1.885-4.353 4.29-4.353c1.104 0 2.014.326 2.794 1.105l2.08-2.08c-1.3-1.17-2.924-1.883-4.874-1.883C3.65 4.586.4 7.835.4 11.8s3.25 7.212 7.214 7.212c4.224 0 6.953-2.988 6.953-7.082 0-.52-.065-1.104-.13-1.624H7.614z"/></svg>
            </span>
            <span class="rrssb-text">google+</span>
        </a>
    </li>

    <li class="rrssb-tumblr">
        <a href="http://tumblr.com/share/link?url={{ shareUrl | url_encode }}&name={{ 'Measure your coolness on steameter.com' | url_encode }}" class="popup">
            <span class="rrssb-icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><path d="M18.02 21.842c-2.03.052-2.422-1.396-2.44-2.446v-7.294h4.73V7.874H15.6V1.592h-3.714s-.167.053-.182.186c-.218 1.935-1.144 5.33-4.988 6.688v3.637h2.927v7.677c0 2.8 1.7 6.7 7.3 6.6 1.863-.03 3.934-.795 4.392-1.453l-1.22-3.54c-.52.213-1.415.413-2.115.455z"/></svg>
            </span>
            <span class="rrssb-text">tumblr</span>
        </a>
    </li>

    <li class="rrssb-vk">
        <a href="http://vk.com/share.php?url={{ shareUrl | url_encode }}" class="popup">
            <span class="rrssb-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="70 70 378.7 378.7"><path d="M254.998 363.106h21.217s6.408-.706 9.684-4.23c3.01-3.24 2.914-9.32 2.914-9.32s-.415-28.47 12.796-32.663c13.03-4.133 29.755 27.515 47.482 39.685 13.407 9.206 23.594 7.19 23.594 7.19l47.407-.662s24.797-1.53 13.038-21.027c-.96-1.594-6.85-14.424-35.247-40.784-29.728-27.59-25.743-23.126 10.063-70.85 21.807-29.063 30.523-46.806 27.8-54.405-2.596-7.24-18.636-5.326-18.636-5.326l-53.375.33s-3.96-.54-6.892 1.216c-2.87 1.716-4.71 5.726-4.71 5.726s-8.452 22.49-19.714 41.618c-23.77 40.357-33.274 42.494-37.16 39.984-9.037-5.842-6.78-23.462-6.78-35.983 0-39.112 5.934-55.42-11.55-59.64-5.802-1.4-10.076-2.327-24.915-2.48-19.046-.192-35.162.06-44.29 4.53-6.072 2.975-10.757 9.6-7.902 9.98 3.528.47 11.516 2.158 15.75 7.92 5.472 7.444 5.28 24.154 5.28 24.154s3.145 46.04-7.34 51.758c-7.193 3.922-17.063-4.085-38.253-40.7-10.855-18.755-19.054-39.49-19.054-39.49s-1.578-3.873-4.398-5.947c-3.42-2.51-8.2-3.307-8.2-3.307l-50.722.33s-7.612.213-10.41 3.525c-2.488 2.947-.198 9.036-.198 9.036s39.707 92.902 84.672 139.72c41.234 42.93 88.048 40.112 88.048 40.112"/></svg>
            </span>
            <span class="rrssb-text">vk.com</span>
        </a>
    </li>
</ul>

src/AppBundle/Resources/views/User/userbar.html.twig
{% set siteUrl = 'http://' ~ app.request.host %}
{% set userbarPath = siteUrl ~ path('user_bar', { hash: app.user.hash }) %}

<h2>or grab this awesome userbar:</h2>

<div class="user-bar">
    <img src="{{ userbarPath }}" id="userbar" />
</div>

<div class="clearfix"></div>

<p>
    <br />
    the userbar is updated automatically each time you achieve a new rating.
    just put it in your forum signature:
    <br /><br />
</p>

<p>
    image url:
    <input type="text" value="{{ userbarPath }}" />
</p>

<p>
    html code:
    <input type="text" value="{{ '<a href="' ~ siteUrl ~ '" target="_blank"><img src="' ~ userbarPath ~ '" alt="' ~ siteUrl ~ '" border="0"></a>' }}" />
</p>

<p>
    &nbsp;&nbsp;bb code:
    <input type="text" value="{{ '[url=' ~ siteUrl ~ '][img]' ~ userbarPath ~ '[/img][/url]' }}" />
    <br />
</p>